# File: .gitlab-ci.yml
default:
    image: google/cloud-sdk:alpine
    before_script:
        - gcloud config set project $GCP_PROJECT_ID #Set the GCP Project ID to the variable name
        - echo $GCP_SERVICE_ACCOUNT > gcloud-service-key.json # Save Google cloud contents in a temporary json file
        - cat gcloud-service-key.json
        - gcloud auth activate-service-account --key-file gcloud-service-key.json # Activate your service account
        # - gcloud auth configure-docker # Configure docker environment

include:
    - local: '/payments-service/.gitlab-ci.yml'