# File: payments-service/.gitlab-ci.yml
variables:
  SERVICE_NAME: "payments-service"
default:
    image: google/cloud-sdk:alpine
    before_script:
        - gcloud config set project $GCP_PROJECT_ID #Set the GCP Project ID to the variable name
        - echo $GCP_SERVICE_ACCOUNT > gcloud-service-key.json # Save Google cloud contents in a temporary json file
        - cat gcloud-service-key.json
        - gcloud auth activate-service-account --key-file gcloud-service-key.json # Activate your service account

build:
    stage: build
    script:
        - gcloud builds submit ./Dockerfile --tag gcr.io/$GOOGLE_CLOUD_PROJECT/$SERVICE_NAME

deploy:
    stage: deploy
    script:
        - gcloud run deploy $SERVICE_NAME --image gcr.io/$GOOGLE_CLOUD_PROJECT/$SERVICE_NAME --platform managed --region asia-east1 --allow-unauthenticated