# File: payments-service/.gitlab-ci.yml
variables:
  SERVICE_NAME: "payments-service"

build:
    stage: build
    script:
        - gcloud builds submit ./Dockerfile --tag gcr.io/$GOOGLE_CLOUD_PROJECT/$SERVICE_NAME

deploy:
    stage: deploy
    script:
        - gcloud run deploy $SERVICE_NAME --image gcr.io/$GOOGLE_CLOUD_PROJECT/$SERVICE_NAME --platform managed --region asia-east1 --allow-unauthenticated